name: Pull Request

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-android:
    needs: test
    uses: ./.github/workflows/build-android.yml

  build-ios:
    needs: test
    uses: ./.github/workflows/build-ios.yml

  build-web:
    needs: test
    uses: ./.github/workflows/build-web.yml
